const SubjHead = ['Charles' , 'Darwin' , 'English' , 'Sussex' , 'Sticky' , 'Ithazmus' , 'Charles' , 'Darwin' , 'Darwin' , 'Right' , 'Darwin' , 'So' , 'Darwin' , 'First' , 'Trenum' , 'Riggs' , 'Darwin' , 'Darwin' , 'Darwin' , 'Drocera' , 'Darwin' , 'Drocera' , 'Drocera' , 'Darwin' , 'Venus' , 'Flytrap' , 'Venus' , 'Flytrap' , 'Darwin' , 'Darwin' , 'Darwin' , 'Holden' , 'Sander' , 'Berden' , 'Sanderson' , 'University' , 'London' , 'Darwin' , 'University' , 'Bonn' , 'Alexander' , 'Volkov' , 'Oakwood' , 'University' , 'Alabama' , 'Dionaea' , 'Ithmus' , 'Darwin' , 'I' , 'And I' , 'You' , 'And you' , 'We' , 'Nobody'];

const NounHead = ['scientist' , 'writer' , 'book' , 'investigation' , 'skill' , 'thriller' , 'writer' , 'backdrop' , 'wilderness' , 'summer' , 'day' , 'fact' , 'solution' , 'mystery' , 'beginning' , 'evidence' , 'future' , 'book' , 'riddle' , 'spatula' , 'sundew' , 'soil' , 'wet' , 'wilderness' , 'feature' , 'spatula' , 'round' , 'leaf' , 'fur' , 'dew' , 'surface' , 'fur' , 'way' , 'action' , 'expression' , 'nature' , 'number' , 'tentacle' , 'droplet' , 'perspiration' , 'name' , 'sun' , 'dew' , 'droplet' , 'liquid' , 'sunlight' , 'middle' , 'end' , 'object' , 'fur' , 'stimulus' , 'hair' , 'hair' , 'center' , 'object' , 'size' , 'type' , 'object' , 'plant' , 'process' , 'stimulation' , 'pass' , 'variety' , 'sensitivity' , 'appetite' , 'spatula' , 'spatula' , 'heart' , 'food' , 'roast' , 'beef' , 'milk' , 'cheese' , 'breath' , 'sputum' , 'sensitization' , 'power' , 'spatula' , 'measure' , 'woman' , 'hair' , 'friend' , 'scale' , 'lab' , 'street' , 'trace' , 'living' , 'insect' , 'name' , 'end' , 'tentacle' , 'struggle' , 'trigger' , 'insect' , 'forming' , 'stomach' , 'organic' , 'reaction' , 'system' , 'food' , 'glue' , 'gastric' , 'fluid' , 'stomach' , 'process' , 'link' , 'benefit' , 'spatula' , 'study' , 'tortane' , 'layer' , 'juicy' , 'cabbage' , 'liquid' , 'water' , 'side' , 'effect' , 'specialist' , 'experimenter' , 'experiment' , 'result' , 'detail' , 'heat' , 'food' , 'wing' , 'leaf' , 'islet' , 'hair' , 'leaf' , 'hair' , 'hair' , 'trap' , 'device' , 'energy' , 'wind' , 'condition' , 'one-tenth' , 'force' , 'point' , 'insect' , 'surface' , 'case' , 'prey' , 'leaf' , 'tissue' , 'stimulus' , 'movement' , 'heat' , 'method' , 'mechanism' , 'movement' , 'fluid' , 'movement' , 'wave' , 'cell' , 'aggregation' , 'plant' , 'wave' , 'source' , 'excitement' , 'plant' , 'biologist' , 'age' , 'stimuli' , 'potential' , 'physiology' , 'professor' , 'stimuli' , 'analogy' , 'line' , 'professor' , 'conclusion' , 'movement' , 'ten-piece' , 'muscle' , 'contraction' , 'century' , 'mechanism' , 'person' , 'hair' , 'potential' , 'concentration' , 'calcium' , 'heat' , 'hair' , 'potential' , 'charge' , 'cell' , 'safety' , 'assurance' , 'system' , 'movement' , 'leaf' , 'trap' , 'shut' , 'memory' , 'information' , 'behavior' , 'information' , 'brain' , 'prerogative' , 'ability' , 'store' , 'information' , 'investigate' , 'dreams' , 'plant' , 'century' , 'reason' , 'joy'];

const VerbHead = ['was' , 'are' , 'are' , 'be' , 'emerge' , 'covered' , 'pointed' , 'are' , 'are' , 'be' , 'do' , 'move' , 'catch' , 'stop' , 'test' , 'feed' , 'was' , 'were' , 'try' , 'boiled' , 'spit' , 'test' , 'weighed' , 'were' , 'stimulated' , 'attached' , 'served' , 'are' , 'are' , 'did' , 'explore' , 'begin' , 'found' , 'break' , 'are' , 'secrete' , 'analyzed' , 'found' , 'did' , 'find' , 'was' , 'obtain' , 'were' , 'be' , 'make' , 'repeated' , 'came' , 'secrete' , 'absorb' , 'found' , 'was' , 'responsive' , 'fake' , 'did' , 'realize' , 'had' , 'be' , 'close' , 'waste' , 'begin' , 'be' , 'be' , 'open' , 'go' , 'say' , 'checked' , 'observed' , 'thought' , 'was' , 'was' , 'discovered' , 'discovered' , 'produced' , 'studied' , 'activate' , 'was' , 'used' , 'crossed' , 'conveyed' , 'was' , 'was' , 'had' , 'touch' , 'respond' , 'found' , 'was' , 'was' , 'snap' , 'determine' , 'send' , 'have' , 'lost'];

const CON = ['but' , 'and' , 'and' , 'and' , 'and' , 'and' , 'but' , 'and' , 'and' , 'and' , 'but' , 'and' , 'or' , 'And' , 'and' , 'or' , 'and' , 'and' , 'and' , 'and' , 'and' , 'and' , 'and' , 'and' , 'and' , 'and' , 'and' , 'and' , 'and' , 'and' , 'but' , 'or' , 'but' , 'or' , 'or' , 'and' , 'and' , 'and' , 'and' , 'and' , 'But' , 'and' , 'and' , 'and' , 'and'];

const Adv = ['not' , 'only' , 'also' , 'then' , 'constantly' , 'often' , 'presumably' , 'here' , 'then' , 'slowly' , 'tightly' , 'completely' , 'deliberately' , 'not' , 'there' , 'also' , 'then' , 'sometimes' , 'all' , 'Then' , 'even' , 'also' , 'quickly' , 'not' , 'just' , 'then' , 'Therefore' , 'surprisingly' , 'also' , 'even' , 'rather' , 'almost' , 'then' , 'Also' , 'highly' , 'selectively' , 'not' , 'even' , 'not' , 'suddenly' , 'close' , 'Then' , 'tightly' , 'up' , 'very' , 'not' , 'so' , 'far' , 'very' , 'willingly' , 'only' , 'then' , 'first' , 'temporarily' , 'then' , 'Indeed' , 'formerly' , 'also' , 'Perhaps'];

const Adj = ['original' , 'Vegetable' , 'scientific' , 'unknown' , 'surprising' , 'ferocious' , 'such' , 'acidic' , 'sticky' , 'fine' , 'translucent' , 'upper' , 'first' , 'several' , 'carnivorous' , 'total' , 'poetic' , 'short' , 'small' , 'middle' , 'motional' , 'whole' , 'several' , 'several' , 'amazing' , 'sticky' , 'sticky' , 'live' , 'dead' , 'weak' , 'half-caught' , 'such' , 'hard' , 'organic' , 'sticky' , 'precise' , 'low-lying' , 'complete' , 'uncontroversial' , 'sticky' , 'effective' , 'dead' , 'dried' , 'temporary' , 'distinguish' , 'inorganic' , 'chemical' , 'digestive' , 'digestive' , 'nitrogenous' , 'like' , 'human' , 'acidic' , 'peptin-like' , 'similar' , 'adequate' , 'digestive' , 'undernourished' , 'insect-hunting' , 'sticky' , 'early' , 'acidic' , 'nutritious' , 'exciting' , 'lukewarm' , 'interesting' , 'Victorian' , 'diet' , 'rigorous' , 'same' , 'similar' , 'great' , 'microscopic' , 'digestive' , 'irritating' , 'responsive' , 'human' , 'small' , 'ten' , 'second' , 'strong' , 'crushed' , 'digestive' , 'large' , 'difficult' , 'active' , 'effective' , 'excited' , 'evolutionary' , 'same' , 'electric' , 'former' , 'electrical' , 'animal' , 'meticulous' , 'other' , 'animal' , 'second' , 'cumulative' , 'fluid' , 'short-term' , 'future' , 'previous' , 'such' , 'electrical' , '18th'];

const Preposition = ['In' , 'with' , 'of' , 'Although' , 'in' , 'against' , 'of' , 'on' , 'that' , 'in' , 'that' , 'in' , 'Since' , 'of' , 'in' , 'as' , 'of' , 'with' , 'with' , 'with' , 'as' , 'by' , 'of' , 'of' , 'that' , 'while' , 'of' , 'After' , 'of' , 'that' , 'in' , 'in' , 'of' , 'of' , 'from' , 'of' , 'that' , 'in' , 'in' , 'of' , 'at' , 'toward' , 'on' , 'of' , 'through' , 'For' , 'from' , 'of' , 'of' , 'of' , 'on' , 'as' , 'Blow' , 'on' , 'of' , 'of' , 'of' , 'by' , 'on' , 'in' , 'on' , 'in' , 'of' , 'in' , 'as' , 'than' , 'by' , 'after' , 'while' , 'inside' , 'over' , 'from' , 'from' , 'that' , 'that' , 'that' , 'while' , 'of' , 'of' , 'in' , 'between' , 'of' , 'in' , 'from' , 'in' , 'with' , 'than' , 'into' , 'on' , 'than' , 'with' , 'with' , 'in' , 'of' , 'with' , 'on' , 'of' , 'of' , 'that' , 'of' , 'at' , 'of' , 'within' , 'on' , 'of' , 'in' , 'about' , 'of' , 'from' , 'In' , 'of' , 'for' , 'without' , 'as' , 'that' , 'of' , 'of' , 'through' , 'Although' , 'of' , 'of' , 'of' , 'in' , 'than' , 'of' , 'In' , 'that' , 'of' , 'that' , 'of' , 'across' , 'at' , 'of' , 'as' , 'In' , 'of' , 'about' , 'ago' , 'that' , 'that' , 'from' , 'of' , 'of' , 'in' , 'that' , 'by' , 'of' , 'in' , 'about' , 'before' , 'over' , 'within' , 'after' , 'about' , 'as' , 'in' , 'of' , 'in' , 'in'];

const LIST = [SubjHead, NounHead, VerbHead, CON, Adv, Adj, Preposition];

function pick(arr) {
    var idx = Math.floor(Math.random() * arr.length);
    return arr[idx];
}

var words = pick(LIST);

setInterval(function() {
    $("#content").text(pick(words));
}, Math.random() * 2000 + 3000)
